name: Build Docker image

on:
  pull_request:

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          file: Dockerfile
          tags: docker-backup-cron:dev
